app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from app import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),

]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path

from carts import views

app_name='carts'

urlpatterns = [
    path('cart_add/', views.cart_add, name='cart_add'),
    path('cart_change/', views.cart_change, name='cart_change'),
    path('cart_remove/', views.cart_remove, name='cart_remove'),

]

goods/urls.py
from django.urls import path

from goods import views

app_name='goods'

urlpatterns = [
    path('search/', views.catalog, name='search'),
    path('<slug:category_slug>/', views.catalog, name='index'),
    path('product/<slug:product_slug>/', views.product, name='product')
]

goods/models.py
from django.db import models
from django.urls import reverse
from markdownfield.models import MarkdownField, RenderedMarkdownField
from markdownfield.validators import VALIDATOR_STANDARD

class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')

    class Meta:
        db_table = 'category'
        verbose_name= 'Категорию'
        verbose_name_plural= 'Категории'

    def __str__(self):
        return self.name 
    

class Products(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')

    description = MarkdownField(
        rendered_field='description_rendered',
        validator=VALIDATOR_STANDARD,
        blank=True,
        null=True,
        verbose_name='Описание'
    )
    description_rendered = RenderedMarkdownField(null=True)

    image = models.ImageField(upload_to='goods_images', blank=True, null=True, verbose_name='Изображение')
    price = models.DecimalField(default=0.00, max_digits=9, decimal_places=2, verbose_name='Цена')   
    discount = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Скидка в %')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество на складе')   
    category = models.ForeignKey(to=Categories, on_delete=models.CASCADE, verbose_name='Категория')

    class Meta:
        db_table = 'product'
        verbose_name= 'Продукт'
        verbose_name_plural= 'Продукты'
        ordering = ("id",)

    def __str__(self):
        return f'{self.name} Количество - {self.quantity}' 
    
    def get_absolute_url(self):
        return reverse("catalog:product", kwargs={"product_slug": self.slug})
    

    def display_id(self):
        return f'{self.id:05}'
    
    def sell_price(self):
        if self.discount:
            return round(self.price - self.price * self.discount/100,2)
        return self.price

goods/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

from goods.models import Products, Categories
from goods.utils import q_search


def catalog(request, category_slug=None):

    page = request.GET.get('page', 1)
    on_sale = request.GET.get('on_sale', None)
    order_by = request.GET.get('order_by', None)
    query = request.GET.get('q', None)

    current_category_name = "Все товары"

    if category_slug == 'all':
        goods = Products.objects.all()
        current_category_name = "Все товары"
    elif query:
        goods = q_search(query)
        current_category_name = f"Поиск: {query}"
    else:
        category = get_object_or_404(Categories, slug=category_slug)
        current_category_name = category.name
        goods = Products.objects.filter(category=category)

    if on_sale:
        goods = goods.filter(discount__gt=0)

    if order_by and order_by != "default":
        goods = goods.order_by(order_by)

    paginator = Paginator(goods, 6) 
    current_page = paginator.page(int(page))       

    context = {
        "title": "DRY Tech - каталог", 
        "goods": current_page, 
        "slug_url": category_slug,
        "current_category_name": current_category_name,
        "is_on_sale_active": bool(on_sale), 
    }

    return render(request, "goods/catalog.html", context)


def product(request, product_slug):
    product = get_object_or_404(Products, slug=product_slug)
    context = {
        'product': product
    }
    return render(request, "goods/product.html", context=context)

goods/templates/goods/catalog.html
{% extends "base.html" %}
{% load static %}
{% load goods_tags %}


{% block content %}

<div class="row"> {# ОТКРЫВАЕМ ОДИН ОБЩИЙ ROW ДЛЯ КОЛОНОК #}

    <div class="col-lg-3"> {# КОЛОНКА ДЛЯ ФИЛЬТРОВ #}
        <div class="dropdown mb-4">
            <button class="btn btn-outline-secondary dropdown-toggle w-100" type="button" data-bs-toggle="dropdown"
                aria-expanded="false" data-bs-auto-close="outside">
                Фильтры
            </button>

            <form action="{% if request.GET.q %}{% url "catalog:search" %}{% else %}{% url "catalog:index" slug_url %}{% endif %}" method="get" class="dropdown-menu border-0 shadow-sm p-3 w-100"  >
                <div class="form-check mb-2">
                    <input class="form-check-input" type="checkbox" name="on_sale"  id="flexCheckDefault" value="on" 
                    {% if is_on_sale_active %} 
                        checked
                    {% endif %}>
                    {% if request.GET.q %}
                        <input type="hidden" name="q" value="{{ request.GET.q }} ">
                    {% endif %}
                    <label class="form-check-label text-dark" for="flexCheckDefault">
                        Товары по акции
                    </label>
                </div>
                <p class="text-dark mt-3 mb-2 fw-semibold">Сортировать:</p>
                <div class="form-check mb-2">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default" 
                    {%if not request.GET.order_by or request.GET.order_by == 'default' %} 
                        checked 
                    {% endif %}>
                    <label class="form-check-label text-dark" for="flexRadioDefault1">
                        По умолчанию
                    </label>
                </div>
                <div class="form-check mb-2">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="price" 
                    {% if request.GET.order_by == 'price' %} 
                        checked 
                    {% endif %}>
                    <label class="form-check-label text-dark" for="flexRadioDefault2">
                        От дешевых к дорогим
                    </label>
                </div>
                <div class="form-check mb-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="-price" 
                    {% if request.GET.order_by == '-price' %}
                        checked
                    {% endif %}>
                    <label class="form-check-label text-dark" for="flexRadioDefault3">
                        От дорогих к дешевым
                    </label>
                </div>
                <button type="submit" class="btn btn-primary w-100">Применить</button>
            </form>
        </div>

        <div class="card shadow-sm mt-4">
            <div class="card-header bg-white">
                <h5 class="mb-0"><i class="fas fa-th-list me-2"></i>Категории</h5>
            </div>
            <div class="list-group list-group-flush">
                {% tag_categories as categories %}
                {% for category in categories %}
                <a href="{% url "catalog:index" category.slug %}" class="list-group-item list-group-item-action"
                    data-slug="{{ category.slug }}"
                    aria-current="true">{{ category.name }}</a>
                {% endfor %}
            </div>
        </div>
    </div> 

    <div class="col-lg-9"> 
        <h2 class="mb-4 mtrem2 text-center text-md-start">{{ current_category_name }}</h2>
        <div class="row gx-4 gy-4">
            {% for product in goods %}
            <div class="col-lg-4 col-md-6">
                <div class="card h-100 border-0 shadow-sm">
                    {% if product.image %}
                        <img src="{{ product.image.url }}" class="card-img-top p-3" alt="{{ product.name }}">
                    {% else %}
                        <img src="{% static " deps/images/Not found image.png" %}" class="card-img-top p-3"
                        alt="{{ product.name }}">
                    {% endif %}

                    <div class="card-body d-flex flex-column">
                        <p class="product_id mb-1">id: {{ product.display_id }}</p>
                        <a href="{% url "catalog:product" product.slug %}" class="text-decoration-none">
                            <h5 class="card-title text-dark">{{ product.name }}</h5>
                        </a>
                        <p class="card-text text-muted text-truncate mb-3" style="max-width: 200px;">
                            {{ product.description }}
                        </p>
                        
                        <div class="d-flex justify-content-between align-items-center mt-auto pt-2">
                            {% if product.discount %}
                                <div>
                                    <p class="price-text mb-0"><strong>{{ product.sell_price }} руб.</strong></p>
                                    <s class="text-muted">{{ product.price }} руб.</s>
                                </div>
                                <span class="badge bg-warning text-dark me-2">Скидка {{ product.discount }} %</span>
                            {% else %}
                                <p class="price-text mb-0"><strong>{{ product.sell_price }} руб.</strong></p>
                            {% endif %}

                            <a href="{% url "cart:cart_add" %}" class="btn btn-primary add-to-cart" 
                            data-product-id="{{ product.id }}">
                                {% csrf_token %}
                                <i class="fas fa-cart-plus"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

        <nav aria-label="Page navigation example" class="mt-5">
            <ul class="pagination justify-content-center">
                <div class="custom-shadow d-flex">
                    <li class="page-item {% if not goods.has_previous %} disabled {% endif %}">
                        <a class="page-link" href="{% if goods.has_previous %}?{% change_params page=goods.previous_page_number %}
                                {% else %}
                                #
                                {% endif %} ">
                        Назад
                        </a>
                    </li>
                    {% for page in goods.paginator.page_range %}
                        {% if page >= goods.number|add:-2 and page <= goods.number|add:2 %} 
                            <li class="page-item {% if goods.number == page %} active {% endif %}">
                                <a class="page-link" href="?{% change_params page=page %}">{{page}}</a>
                            </li>
                        {% endif %}
                    {% endfor %}

                        <li class="page-item {% if not goods.has_next %} disabled {% endif %}">
                            <a class="page-link" href="{% if goods.has_next %}?{% change_params page=goods.next_page_number %}
                                {% else %}
                                #
                                {% endif %} ">
                            Вперед
                            </a>
                        </li>
                </div>
            </ul>
        </nav>
    </div> {# ЗАКРЫВАЕМ КОЛОНКУ col-lg-9 #}

</div> {# ЗАКРЫВАЕМ ОБЩИЙ ROW #}

{% endblock content %}

goods/templates/goods/product.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="col-lg-12">
        <h2 class="mb-4 text-center text-md-start">Детали товара</h2>
        <div class="card mb-4 border-0 shadow-sm">
            <div class="row g-0">
                <div class="col-md-5">
                    <img src="{{ product.image.url }}"
                        class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1">

                    
                    <div class="mt-3 p-3"> 
                        {% if product.discount %}
                            <div>
                                <p class="price-text mb-0"><strong>{{ product.sell_price }} руб.</strong></p>
                                <s class="text-muted">{{ product.price }} руб.</s>
                            </div>
                            <span class="badge bg-warning text-dark me-2 fs-5">Скидка {{ product.discount }} %</span>
                        {% else %}
                            <p class="price-text mb-0"><strong>{{ product.sell_price }} руб.</strong></p>
                        {% endif %}
                        <br>
                        <a href="{% url "cart:cart_add" %}" 
                        class="btn btn-primary btn-lg mt3 add-to-cart" data-product-id="{{ product.id }}">
                            {% csrf_token %}
                        <i class="fas fa-cart-plus me-2"></i> Добавить в корзину
                        </a>
                    </div>
                </div>

                <div class="col-md-7">
                    <div class="card-body p-4">
                        <p class="product_id mb-2">id: {{ product.display_id }}</p>
                        <h1 class="card-title display-5 fw-bold text-dark mb-3">
                            {{ product.name }}
                        </h1>
                        <p class="card-text lead text-secondary mb-4">
                            {{ product.description_rendered|safe }}
                        </p>
                    </div>
                </div>
                {# ... ваш закомментированный модальный блок ... #}
            </div>
        </div>
    </div>
</div>
{% endblock content %}


                <!-- Увеличить изображение в модальном окне -->
                {% comment %} <div class="modal fade" id="imageModal1" tabindex="-1"
                    aria-labelledby="imageModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered modal-xl">
                        <div class="modal-content border-0 shadow-lg">
                            <div class="modal-header">
                                <h5 class="modal-title" id="imageModal1Label">{{ product.name }}</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Закрыть"></button>
                            </div>
                            <div class="modal-body">
                                <img src="{{ product.image.url }}"
                                    class="img-fluid" alt="Изображение 1">
                            </div>
                        </div>
                    </div>
                </div> 
                
                <a href="{% url "cart:cart_add" %}" 
                    class="btn btn-primary btn-lg mt3 add-to-cart" data-product-id="{{ product.id }}">
                        {% csrf_token %}
                        <i class="fas fa-cart-plus me-2"></i> Добавить в корзину
                    </a>
                {% endcomment %}
                <!-- Увеличить изображение в модальном окне -->